esphome:
  name: schundmeter
  friendly_name: schundmeter

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "secret"

ota:
  password: "secret"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Schundmeter Fallback Hotspot"
    password: "secret"

captive_portal:
###
uart:
  id: mod_bus
  tx_pin: GPIO13 # connected to tx on modbus converter
  rx_pin: GPIO12 # connected to rx on modbus converter
  baud_rate: 9600
  stop_bits: 1
  data_bits: 8

modbus:
  send_wait_time: 2000ms
  id: modbus1

#address chint dtsu666 
modbus_controller:
    address: 0xfe
    modbus_id: modbus1
    update_interval: 1s
    setup_priority: -10

sensor:
 - platform: modbus_controller
   id: chint_voltage_a
   name: "Chint Voltage Phase 1"
   address: 0x0061
   unit_of_measurement: "V"
   register_type: holding
   value_type: U_WORD
   accuracy_decimals: 1
   filters:
     - multiply: 0.1

 - platform: modbus_controller
   id: chint_voltage_b
   name: "chint voltage phase 2"
   address: 0x0062
   unit_of_measurement: "V"
   register_type: holding
   value_type: U_WORD
   accuracy_decimals: 1
   filters:
     - multiply: 0.1

 - platform: modbus_controller
   id: chint_voltage_c
   name: "chint voltage phase 3"
   address: 0x0063
   unit_of_measurement: "V"
   register_type: holding
   value_type: U_WORD
   accuracy_decimals: 1
   filters:
     - multiply: 0.1
    
 - platform: modbus_controller
   id: chint_curent_a
   name: "chint cuurent phase 1"
   address: 0x0064
   unit_of_measurement: "A"
   register_type: holding
   value_type: U_WORD
   accuracy_decimals: 1
   filters:
     - multiply: 0.1

 - platform: modbus_controller
   id: chint_curent_b
   name: "chint current phase 2"
   address: 0x0065
   unit_of_measurement: "A"
   register_type: holding
   value_type: U_WORD
   accuracy_decimals: 1
   filters:
     - multiply: 0.1

 - platform: modbus_controller
   id: chint_curent_c
   name: "chint current phase 3"
   address: 0x0066
   unit_of_measurement: "A"
   register_type: holding
   value_type: U_WORD
   accuracy_decimals: 1
   filters:
     - multiply: 0.1
